import { z } from 'zod';

export const AMCompetitionSchema = z.object({
  federation: z.number().int().default(10),
  nationalcode: z.string().max(16).default('F4507'),
  name: z.string().max(256),
  country: z.number().int().default(2032),
  location: z.string().max(256),
  info: z.string().max(256).default(''),
  startdate: z.coerce.date(),
  enddate: z.coerce.date(),
  referencedate: z.coerce.date(),
  outdoor: z.number().int().min(0).max(1).default(1),
  indoor: z.number().int().min(0).max(1).default(0),
  nonstadium: z.number().int().default(0),
  teampolicy: z.string().length(1).default('0'),
  paralympic: z.number().int().default(0),
  language: z.string().max(2).nullable().default(null),
  pointcalculationrace_default: z.number().int().default(1),
  pointcalculationhorfe_default: z.number().int().default(3),
  pointcalculationvertfe_default: z.number().int().default(2),
  categoriesrecalculateresultforpoints: z.string().default(''),
  seedingmethod_default: z.number().int().default(90),
  seedingmethodparameter_default: z.string().default(''),
  placesinheatsprintstraight_default: z.number().int().default(8),
  placesinheatlongdistance_default: z.number().int().default(20),
  placesingroupfield_default: z.number().int().default(50),
  maxparticipationsperteamincompetition: z.number().int().default(0),
  maxparticipationsperteaminevent_default: z.number().int().default(0),
  maxeventspercompetitor: z.number().int().default(0),
  pointcalculationteam_default: z.number().int().default(60),
  numberofcompetitorsforteampoints_default: z.number().int().default(2),
  placesinheatsprintround_default: z.number().int().default(8),
  attempts_default: z.number().int().default(3),
  startheight_default: z.number().default(0.8),
  intervalheight_default: z.number().int().default(5),
  lanes_array_sprintstraight_default: z.string().default('1;2;3;4;5;6;7;8'),
  lanes_array_sprintround_default: z.string().default('1;2;3;4;5;6;7;8'),
  displayname_default: z.string().default(''),
  image_header: z.instanceof(Uint8Array).nullable().default(null),
  image_footer: z.instanceof(Uint8Array).nullable().default(null),
  displayname_round_default: z.string().default('event - round;;;;'),
  photofinishimage_maxheight: z.number().int().default(0),
  heatduration_default: z.number().default(3),
  athlete_team_default: z.number().int().default(999),
  contact_name: z.string().default(''),
  contact_info: z.string().default(''),
  referee_name: z.string().default(''),
  referee_info: z.string().default(''),
});

export type Competition = z.infer<typeof AMCompetitionSchema>;
